import { FC, ReactNode } from 'react'

import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = {
  children: ReactNode
}

const RootLayout: FC<Props> = ({ children }) => (
  <html lang="ja">
    <body>{children}</body>
  </html>
)

export default RootLayout
